name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Download LiveKit Server
      run: |
        curl -L -o livekit.zip https://github.com/livekit/livekit/releases/download/v1.8.4/livekit_1.8.4_windows_amd64.zip
        7z x livekit.zip -o./server/

    - name: Build Server App
      run: |
        cd server-app-submodule
        go build -o ../server/server-app.exe

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: pnpm install

    - name: Build Electron App
      run: pnpm build:win

    - name: Create Release Archive
      run: |
        cd dist
        7z a -tzip ../release.zip *-setup.exe
        cd ..
        7z a release.zip ./server/*

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: electron-livekit-meet-windows
        path: release.zip
